services:
  - type: web
    name: ecommerce-server
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start

  - type: static
    name: ecommerce-client
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
